### PR TITLE
feat: show fertilizer

### PR DESCRIPTION
**Pull request by Zamiell**
shows fertilizer on tooltip

### CODE REVIEW

**Comment by drewhoener** [comment]
@Zamiell wasn't this already included in #465?

**Comment by Zamiell** [comment]
no

**Comment by drewhoener** [comment]
> no

I just fixed a bug related to showing fertilizer, how is this different?
image

**Comment by drewhoener** [comment]
Ohhhh I think I see, is this for if there's fertilizer but no crop?

**Comment by Zamiell** [comment]
yes, it is for no crop, which was an oversight in my original pr

**Comment by drewhoener** [comment]
makes sense to me, the "no" just didn't give me much info to go on lol
either way, lgtm

**Pull request merged**
