### PR TITLE
SplitScreen, UI Scaling, and Gamepad fixes

### LINKED ISSUE #25: Inaccurate Locations of People, while playing a Coop game as guest
While playing the game in coop mode as guest the map still shows every person on the map. But just at there default home location, not the location, where they should be.

### LINKED ISSUE #27: Scaling UI makes clicking buttons impossible
If you scale the UI clicking on options menu, billboard is not where the graphics are (so you can't click them)
Scaling back to 100% makes them work as intented

Also the Pet animal icons are 'off'

Reproduce by scaling your UI

### PR DESCRIPTION
**Pull request by DiscipleOfEris**
This is a manual merge of my fixes for cdaragorn's version, https://github.com/cdaragorn/Ui-Info-Suite/pull/61 for this fork.

Way too much work.

Fixes #25, fixes #27

### CODE REVIEW

**Comment by n1spro** [comment]
sometimes the icon is not displayed above the animal that can be stroked

**Comment by Annosz** [comment]
Thanks for taking your time and making this fix!

I will start reviewing this PR, and when it's merged, I will create a new release and link it in the original mods description page - hopefully people will be able to use your changes way before cdaragon has time to merge it.

I'm sorry you had to work too much with the manual merge. Originally, when I created this project is september, cdaragon was missing for almost a year, so I thought this will be a replacement mod and no compatibility is needed with the original mod. Since then it turned out it was a bad idea, because the original repo also has some activity.

**Comment by friederschueler** [comment]
@DiscipleOfEris Wow thank you very much, I was thinking of doing it, but I just had time to view some of the differences of the mods. I will review this asap and hopefully learn more :) I really appreciate your effort!

@Annosz I only know about this mod because of github. Maybe upload it to nexusmod etc. to make it more visible.
cdaragorn did upload a new version of his mod yesterday. But without the 1.5 coop fixes discipleoferis provided :( he also said that we shouldn't expect too much from him. So if this mod is really more active, maybe we can get some community driven version rolling with quicker updates. But people are not used to clone repositories and building mods, so we should provide a release for "normal" people with the coop fixes. I think quite a lot of people are playing this split screen.

**Review by Annosz — APPROVED** [review]
Well, of course it's hard to review a big change like this, but I tried every feature with changed UI scales and it worked fine in every cases. I couldn't reproduce the bug with the animal petting icons mentioned earlier.

I can't test the split screen functions, because I don't have a controller (please correct me if it's not needed for it, I just Googled "how to play Stardew Valley split-screen"), but as I see, from the use of PerScreen, if everything work for one screen it will most likel will for two...

**Pull request merged**
