### PR TITLE
Release version 2.2.10

### PR DESCRIPTION
**Pull request by tqdv**
- Gamepad controls for the mod options menu page (GitHub pull request #329) 
- Rework upgraded tool icon to handle trash cans (GitHub pull request #303)
- Update ko.json (Github pull request tqdv/UIInfoSuite2#1)
- Placeholder translations for gamepad menu and Robin house upgrade
- Load the file in the asset -> Asset folder
- Configure Woodpecker CI (for my instance hosted at woodpecker.kawa.tf)

### CODE REVIEW

**Comment by drewhoener** [comment]
Is this still a draft? Wondering if it'll get merged soon @tqdv

**Comment by tqdv** [comment]
@drewhoener It's actually released and all, but GitHub doesn't let me merge it.

**Comment by drewhoener** [comment]
oh excellent, I wanted to do some refactoring, but didn't want to do it right before a big PR

**Comment by tqdv** [comment]
@drewhoener Please use the [tqdv-2.2.10](https://github.com/tqdv/UIInfoSuite2/tree/tqdv-2.2.10) branch as the upstream branch if you're going to do refactoring.

I'll figure out how to proceed, but I've been a bit busy recently.

**Comment by drewhoener** [comment]
> @drewhoener Please use the [tqdv-2.2.10](https://github.com/tqdv/UIInfoSuite2/tree/tqdv-2.2.10) branch as the upstream branch if you're going to do refactoring.
> 
> I'll figure out how to proceed, but I've been a bit busy recently.

Sounds good to me, should I PR it to your repo?

**Review by drewhoener — APPROVED** [review]

**Pull request merged**
