### PR TITLE
Add birthday i18n and update Chinese localization

### PR DESCRIPTION
**Pull request by baka-gourd**
I try to translation the tip of NPC's birthday, but its in hard code.
This pr makes the entry localizable, but unfortunately I cloned the library and found that I could not restore it.

Therefore, **this change has not been validated. It may be necessary for you to test it**.
Sorry for the trouble!

ps: If you can get the localized name of the npc, I hope to change `_birthdayNPC.Name` to localized name:P

### CODE REVIEW

**Comment by baka-gourd** [comment]
@Annosz

**Comment by baka-gourd** [comment]
if need more information, please ask directly here:d

**Comment by Annosz** [comment]
Yeah, I just got around to accept the new changes, thanks for making this translation! :)

I can see where the problem is with the hardcoded value, but I think it will be good as you solved it. I will merge this too, test it and update the other files with the new LanguageKey for the new release.

**Comment by baka-gourd** [comment]
> Yeah, I just got around to accept the new changes, thanks for making this translation! :)
> 
> I can see where the problem is with the hardcoded value, but I think it will be good as you solved it. I will merge this too, test it and update the other files with the new LanguageKey for the new release.

Thank you for your reply! Unfortunately, my visual studio doesn't have the ability to restore stardew valley, so I can't submit the tested version to you, sorry for your trouble!

**Review by Annosz — APPROVED** [review]

**Comment by Annosz** [comment]
Thanks! Only fix that was needed is that the LanguageKeys.NpcBirthday needed to be called like _helper.SafeGetString(LanguageKeys.NpcBirthday) to get the correct message :)

(And finally you made me to do the refactor on the Birthday file too, with the regions and unified constructor and methods, so thanks for that too)

**Comment by baka-gourd** [comment]
> Thanks! Only fix that was needed is that the LanguageKeys.NpcBirthday needed to be called like _helper.SafeGetString(LanguageKeys.NpcBirthday) to get the correct message :)
> 
> (And finally you made me to do the refactor on the Birthday file too, with the regions and unified constructor and methods, so thanks for that too)

Thanks for your merge.

**Comment by baka-gourd** [comment]
@Annosz 
```csharp
		[XmlIgnore]
		public string displayName
		{
			get
			{
				string result;
				if ((result = this._displayName) == null)
				{
					result = (this._displayName = this.translateName(this.name));
				}
				return result;
			}
			set
			{
				this._displayName = value;
			}
		}
```
look this: the `_birthdayNPC.Name` maybe mean displayName to localization.
This is a legacy issue， if want to localize ALL.

**Pull request merged**
