### PR TITLE
Update LocationOfTownsfolk.cs

### PR DESCRIPTION
**Pull request by VashtiH**
This should fix issues in which Lewis is not shown on the map, and Caroline is not shown in the correct position when in her sunroom.

### CODE REVIEW

**Comment by tqdv** [comment]
Looks good for the sunroom entry :+1: 

For Lewis, isn't he already handled by `isVillager()` ?

**Comment by VashtiH** [comment]
> Looks good for the sunroom entry 👍
> 
> For Lewis, isn't he already handled by `isVillager()` ?

Maybe, but I have yet to ever find him on the map, so I figured he isn't.  I could be wrong!

**Comment by tqdv** [comment]
So I did some testing, and Lewis is indeed handled by the `isVillager()` check. He appears normally in his mansion and all, so I don't know why you can't find him.
 
For the sunroom code, I just noticed that the submitted code has two `>`s instead of one.

Could you fix that extra angle bracket, and remove the additional check for Lewis ? Then I'll be able to merge your pull request. Or I could do it myself it you want :)

**Comment by VashtiH** [comment]
I think I've got it fixed now.  The Lewis thing must be something with my game.  Thanks for reviewing!

**Review by tqdv — APPROVED** [review]
Should be good to go now!

**Pull request merged**
